### ISSUE TITLE
Celery Worker fixes

### ISSUE THREAD

**Issue by awest1339** [mitre/multiscanner#114]
* Remove the "flush_every" options from the default config.
  * No longer needed due to removal of batching.
* https://github.com/mitre/multiscanner/blob/master/utils/celery_worker.py#L143
  * This should use the module_lists that is passed in (if there is one) to generate the scan config metadata object. Otherwise, this data will be inaccurate if the user passes in a custom module list.
* https://github.com/mitre/multiscanner/blob/master/utils/celery_worker.py#L187
  * The report should be indexed into ES before the task tracking DB is updated. As it is now, the worker could fail to index the report and then still update the task DB w/ a Task Status of Complete (instead of Failed).
  * Additionally, this could lead to a race condition where the task status is complete but the report is not yet in ES.

**Comment by ptcNOP** [comment]
`storage.store` should probably be wrapped in a try-except with a generic `StorageError`, right? Otherwise, the case of the task db not matching the storage could still happen.

**Comment by awest1339** [comment]
Not sure if the storage.store needs to be wrapped in a try block because the error handling is done in the store method. Thoughts?
