### ISSUE TITLE
Fileshare with analyticsmachine via SCP

### ISSUE THREAD

**Issue by benlarsendk** [mitre/multiscanner#119]
Instead of being forced to have a network share with the analytcsmachine, wouldn't it be able to use SCP? It's already using SSH for comm's? :)

**Comment by Drewsif** [comment]
Theres no technical reason why we couldn't. The main reason we picked a file share is it gave us the most options for people to use what they wanted to on the back end. The problem with SCP is that its a 1 to 1 and there are use cases where we need 1 to Many.

You could try using [sshfs](https://github.com/libfuse/sshfs), that might simplify your setup.
