### ISSUE TITLE
files and report format suppported by scanner????

### ISSUE THREAD

**Issue by cuckoo-linux** [mitre/multiscanner#153]
1.Multi scanner which types of files???exe or windows files can also be tested or not??
2.report is in json format which is hard to understand,is anyother format be supported?

**Comment by Drewsif** [comment]
1. Multiscanner is file agnostic. The modules will work with most common file formats, but it depends on the module the level of information you get.
2. The web version has a ui that you might find easier than json. More info here https://multiscanner.readthedocs.io/en/latest/install.html
