### ISSUE TITLE
Error after calling docker-compose up

### ISSUE THREAD

**Issue by asingh270** [mitre/multiscanner#204]
Getting this error after building and running docker-compose up:

`Traceback (most recent call last):
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
api_1      |     ws.require(__requires__)
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
api_1      |     needed = self.resolve(parse_requirements(requirements))
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
api_1      |     raise VersionConflict(dist, req).with_context(dependent_req)
api_1      | pkg_resources.ContextualVersionConflict: (urllib3 1.25.3 (/usr/lib/python3.7/site-packages), Requirement.parse('urllib3<1.25,>=1.24.2'), {'elasticsearch-curator'})
api_1      | 
api_1      | During handling of the above exception, another exception occurred:
api_1      | 
api_1      | Traceback (most recent call last):
api_1      |   File "/usr/bin/multiscanner-api", line 6, in <module>
api_1      |     from pkg_resources import load_entry_point
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
api_1      |     @_call_aside
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
api_1      |     f(*args, **kwargs)
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
api_1      |     working_set = WorkingSet._build_master()
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
api_1      |     return cls._build_from_requirements(__requires__)
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
api_1      |     dists = ws.resolve(reqs, Environment())
api_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
api_1      |     raise DistributionNotFound(req, requirers)
api_1      | pkg_resources.DistributionNotFound: The 'urllib3<1.25,>=1.24.2' distribution was not found and is required by elasticsearch-curator
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
web_1      |     ws.require(__requires__)
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
web_1      |     needed = self.resolve(parse_requirements(requirements))
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
web_1      |     raise VersionConflict(dist, req).with_context(dependent_req)
web_1      | pkg_resources.ContextualVersionConflict: (urllib3 1.25.3 (/usr/lib/python3.7/site-packages), Requirement.parse('urllib3<1.25,>=1.24.2'), {'elasticsearch-curator'})
web_1      | 
web_1      | During handling of the above exception, another exception occurred:
web_1      | 
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/bin/multiscanner-web", line 6, in <module>
web_1      |     from pkg_resources import load_entry_point
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
web_1      |     @_call_aside
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
web_1      |     f(*args, **kwargs)
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
web_1      |     working_set = WorkingSet._build_master()
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
web_1      |     return cls._build_from_requirements(__requires__)
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
web_1      |     dists = ws.resolve(reqs, Environment())
web_1      |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
web_1      |     raise DistributionNotFound(req, requirers)
web_1      | pkg_resources.DistributionNotFound: The 'urllib3<1.25,>=1.24.2' distribution was not found and is required by elasticsearch-curator
`

**Comment by abhinavbom** [comment]
got this resolved. It was a version conflict.

**Comment by HHJazi** [comment]
> got this resolved. It was a version conflict.

Can you please tell me how did you manage to fix this problem? I am having the same issue..

**Comment by malvidin** [comment]
This issue was likely closed prematurely. The requirements.txt file does not enforce a version of elasticsearch-curator that works with the enforced version of elastic.

Try adding this to requirement.txt
`elasticsearch-curator<5.7.0
`
Adding -t 300 to docker-compose.yml might fix other BusyBox issues.
`command: /wait-for-it.sh elastic:9200 -t 300 -- multiscanner-api`
