### ISSUE TITLE
YaraScan Recurse dir should be a config option

### ISSUE THREAD

**Issue by awest1339** [mitre/multiscanner#41]
* https://github.com/mitre/multiscanner/blob/master/modules/Signature/YaraScan.py#L38
* Users should be able to specify whether they want the yara module to recursively find rules. 
* Currently, if a user has a .yar file that includes a set of subdirectories, the rules will be added twice, resulting in duplicate hits

**Comment by Drewsif** [comment]
Fixed by 833cee45b4669637424bc69b452a02672dfd9acd
