### ISSUE TITLE
Drop tqdm requirement?

### ISSUE THREAD

**Issue by clenk** [mitre/multiscanner#51]
We have a Pull Request failing Travis because of one of our dependencies: https://travis-ci.org/mitre/multiscanner/jobs/287253373 We require `tqdm`, which requires `paramiko`, which requires `cryptography`, which [dropped  Py3.3 support in version 2.0](https://cryptography.io/en/latest/changelog/#v2-0). However, [it doesn't look like we're using tqdm anywhere](https://github.com/mitre/multiscanner/search?utf8=%E2%9C%93&q=tqdm&type=), so maybe can just drop this dependency instead of dropping 3.3 support?

cc @Drewsif @awest1339

**Comment by Drewsif** [comment]
So 3.3 [is EOL](https://www.python.org/dev/peps/pep-0398/#x-end-of-life). Paramiko is the ssh library that the windows modules are using. I'm ok dropping 3.3 support knowing that it's EOL.

**Comment by awest1339** [comment]
Agree with dropping Python 3.3 support.
Python 3.3 lifespan here: https://www.python.org/dev/peps/pep-0398/#lifespan

**Comment by awest1339** [comment]
⚰️
