### ISSUE TITLE
Multiscanner doesn't find valid module path

### ISSUE THREAD

**Issue by Kcrong** [mitre/multiscanner#60]
Even though I have all modules, the multiscanner still couldn't find it.

I just execute script below, 

```python
import multiscanner
output = multiscanner.multiscan(['/file/path/a.out'])
Results = multiscanner.parse_reports(output, python=True)
```

And it outputs

![image](https://user-images.githubusercontent.com/13450715/33228973-ddf887ba-d208-11e7-81ff-81c5b18c9117.png)

**Comment by Drewsif** [comment]
Fixed by #61
