### ISSUE TITLE
install.sh fails to install yara / yara-python correctly

### ISSUE THREAD

**Issue by awest1339** [mitre/multiscanner#78]
On CentOS 7, the install.sh script fails to install yara

**Comment by ptcNOP** [comment]
This seem to stem from the version of libtool (v2.4.2) in EPEL, and the fact that AC_CONFIG_AUX_DIR is not set in YARA's configure.ac. 

Possible solutions:

1. Just run `./bootstrap` twice on CentOS systems.
1. PR to YARA to set AC_CONFIG_AUX_DIR=[.]
   - Not sure if there's a good reason why it's _not_ set.
1. Try to install a different version of libtool on CentOS systems before YARA installation.
1. Remove YARA installation from install.sh

**Comment by awest1339** [comment]
Fixed by https://github.com/mitre/multiscanner/pull/76.
